# Site settings
title: Pisi Linux
name: Pisi Linux
email: dist.mailto@yandex.com
address: Türkiye
description:
  Pisi Linux; Pisi tabanlı son Pardus sürümünü temel alan, özgür yazılım topluluğu tarafından geliştirilen, bilgisayar kulanıcılarına kurulum, yapılandırma ve kullanım konusunda kolaylık sağlamaya çalışan, onların temel masaüstü gereksinimlerini karşılamayı amaçlayan, son kullanıcı odaklı bir GNU/Linux dağıtımıdır.
  
encoding: UTF-8
languages: ['en', 'tr']
language_default: 'tr'
baseurl: 
url: 
slack_address: http://pisi.slack.com
forum_address: http://forum.pisilinux.org
bugs_address: http://bugs.pisilinux.org
wiki_address: http://wiki.pisilinux.org
facebook_address: https://www.facebook.com/pisilinux
twitter_address: https://twitter.com/pisilinux
github_address: https://github.com/pisilinux
google_address: https://plus.google.com/communities/113565681602860915332
gems: [jekyll-seo-tag]

collections:
  services:
    output: true


# Build settings
markdown: kramdown
